# Site settings
title: Jolene Lai - Fine Artist
email: enelojial@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Paintings and Illustrations by Jolene Lai
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.enelojial.com" # the base hostname & protocol for your site
twitter_username: enelojial

# Build settings
markdown: kramdown

permalink: /:categories/:title

defaults:
  -
    scope:
      path: "illustrations"
    values:
      categories: illustrations
  -
    scope:
      path: "paintings"
    values:
      categories: paintings

gems:
    - jekyll-redirect-from
    - jekyll-sitemap

sass:
    style: :compressed
